WebStore/Components/BrandsViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities;
using WebStore.Infrastructure.Interfaces;
using WebStore.Infrastructure.Map;
using WebStore.ViewModels;

namespace WebStore.Components
{
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BrandsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke() => View(GetBrands());

        private IEnumerable<BrandViewModel> GetBrands() => _ProductData.GetBrands().Select(brand => brand.CreateModel());
    }
}

WebStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Infrastructure.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _CartService;
        private readonly IOrderService _OrderService;

        public CartController(ICartService CartService, IOrderService OrderService)
        {
            _CartService = CartService;
            _OrderService = OrderService;
        }

        public IActionResult Details()
        {
            var model = new DetailsViewModel
            {
                CartViewModel = _CartService.TransformCart(),
                OrderViewModel = new OrderViewModel()
            };
            return View(model);
        }

        public IActionResult DecrementFromCart(int id)
        {
            _CartService.DecrementFromCart(id);
            return RedirectToAction("Details");
        }

        public IActionResult RemoveFromCart(int id)
        {
            _CartService.RemoveFromCart(id);
            return RedirectToAction("Details");
        }

        public IActionResult RemoveAll()
        {
            _CartService.RemoveAll();
            return RedirectToAction("Details");
        }

        public IActionResult AddToCart(int id)
        {
            _CartService.AddToCart(id);
            return RedirectToAction("Details");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult CheckOut(OrderViewModel model)
        {
            if (!ModelState.IsValid)
                return View(nameof(Details), new DetailsViewModel
                {
                    CartViewModel = _CartService.TransformCart(),
                    OrderViewModel = model
                });

            var order = _OrderService.CreateOrder(model, _CartService.TransformCart(), User.Identity.Name);

            _CartService.RemoveAll();

            return RedirectToAction("OrderConfirmed", new { id = order.Id });
        }

        public IActionResult OrderConfirmed(int id)
        {
            ViewBag.OrderId = id;
            return View();
        }
    }
}

WebStore/Controllers/CatalogController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities;
using WebStore.Infrastructure.Interfaces;
using WebStore.Infrastructure.Map;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductData _ProductData;

        public CatalogController(IProductData ProductData) => _ProductData = ProductData;

        public IActionResult Shop(int? SectionId, int? BrandId)
        {
            var products = _ProductData.GetProducts(new ProductFilter
            {
                SectionId = SectionId,
                BrandId = BrandId
            });

            var catalog_model = new CatalogViewModel
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Products = products.Select(ProductViewModelMapper.CreateViewModel)
            };

            return View(catalog_model);
        }

        public IActionResult ProductDetails(int id)
        {
            var product = _ProductData.GetProductById(id);

            return product is null
                ? (IActionResult) NotFound()
                : View(new ProductViewModel
                {
                    Id = product.Id,
                    Name = product.Name,
                    Price = product.Price,
                    Order = product.Order,
                    ImageUrl = product.ImageUrl,
                    Brand = product.Brand?.Name
                });
        }
    }
}

WebStore/Controllers/EmployesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Infrastructure.Interfaces;
using WebStore.Models;

namespace WebStore.Controllers
{
    //[Route("Users/[action]")]
    [Authorize]
    public class EmployesController : Controller
    {
        private readonly IEmployeesData _EmployeesData;

        public EmployesController(IEmployeesData EmployeesData) => _EmployeesData = EmployeesData;

        public IActionResult Index() => View(_EmployeesData.GetAll());

        //[Route("Info/{id}")]
        //[ActionName("EmployesDetails")]
        public IActionResult Details(int id)
        {
            var employe = _EmployeesData.GetById(id);
            return employe == null 
                ? (IActionResult) NotFound() 
                : View("EmployeeView", employe);
        }

        [Authorize(Roles = Domain.Entities.User.RoleAdmin)]
        public IActionResult Edit(int? id)
        {
            Employee employee;
            if (id != null)
            {
                employee = _EmployeesData.GetById((int)id);
                if (employee is null)
                    return NotFound();
            }
            else
            {
                employee = new Employee();
            }

            return View(employee);
        }

        [HttpPost]
        [Authorize(Roles = Domain.Entities.User.RoleAdmin)]
        public IActionResult Edit(Employee employee, [FromServices] IMapper mapper)
        {
            if(employee.Age < 18)
                ModelState.AddModelError("Age", "Возраст слишком маленький");

            if (employee.Age > 120)
                ModelState.AddModelError("Age", "Странный возраст");

            //if(employee.Age % 2 == 0)
            //    ModelState.AddModelError("", "Чётный возраст");

            if (!ModelState.IsValid) return View(employee);

            if (employee.Id > 0)
            {
                var db_employee = _EmployeesData.GetById(employee.Id);
                if (db_employee is null)
                    return NotFound();

                //AutoMapper.Mapper.Map(employee, db_employee);
                mapper.Map(employee, db_employee);

                //db_employee.FirstName = employee.FirstName;
                //db_employee.SurName = employee.SurName;
                //db_employee.Patronymic = employee.Patronymic;
                //db_employee.Age = employee.Age;
            }
            else
                _EmployeesData.AddNew(employee);

            _EmployeesData.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Domain.Entities.User.RoleAdmin)]
        public IActionResult Delete(int id)
        {
            var employee = _EmployeesData.GetById(id);
            if (employee is null) return NotFound();
            _EmployeesData.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WebStore/Views/Shared/Partial/_FeaturesItems.cshtml
@model IEnumerable<WebStore.ViewModels.ProductViewModel>

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Features Items</h2>

    @foreach (var product in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/images/shop/@product.ImageUrl" alt="@product.Name" />
                        <h2>@product.Price.ToString("C")</h2>
                        <p>@product.Name</p>
                        <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@product.Id"
                           class="btn btn-default add-to-cart">
                            <i class="fa fa-shopping-cart"></i>Добавить в корзину
                        </a>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@product.Price.ToString("C")</h2>
                            <p><a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@product.Id">@product.Name</a></p>
                            <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@product.Id"
                               class="btn btn-default add-to-cart">
                                <i class="fa fa-shopping-cart"></i>Добавить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Добавить в список желаний</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Добавить к сравнению</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }
</div><!--features_items-->

WebStore/Views/Shared/Partial/_Footer.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Описание компании</p>
                    </div>
                </div>
                <div class="col-sm-7" style="display: none">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Круг рук</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="images/home/map.png" alt="" />
                        <p>Адрес компании</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Сервис</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Помощь</a></li>
                            <li><a asp-controller="Home" asp-action="ContactUs">Контакты</a></li>
                            <li><a href="#">Статус заказа</a></li>
                            <li><a href="#">Сменить расположение</a></li>
                            <li><a href="#">ЧаВо</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Быстрый заказ</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Рубашки</a></li>
                            <li><a href="#">Мужские товары</a></li>
                            <li><a href="#">Женские товары</a></li>
                            <li><a href="#">Подарочные сертификаты</a></li>
                            <li><a href="#">Обувь</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Правила</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Правила использования</a></li>
                            <li><a href="#">Политика конфиденциальности</a></li>
                            <li><a href="#">Правила возврата</a></li>
                            <li><a href="#">Оплата</a></li>
                            <li><a href="#">Сертификаты</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>О компании</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Информация</a></li>
                            <li><a href="#">Карьера</a></li>
                            <li><a href="#">Расположение магазинов</a></li>
                            <li><a href="#">Программа лояльности</a></li>
                            <li><a href="#">Торговая марка</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>О магазине</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6" style="display: none">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a asp-controller="Home" asp-action="Index"><img src="images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        @*<div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>*@

                        @*<div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>*@
                    </div>
                </div>
                <div class="col-sm-8">
                    @*@await Component.InvokeAsync("UserInfo")*@
                    <vc:user-info/>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a asp-controller="Home" asp-action="Index" class="active">Главная</a></li>
                            <li class="dropdown">
                                <a href="#">Магазин<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a asp-controller="Catalog" asp-action="Shop">Товары</a></li>
                                    <li><a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="1">Детали товара</a></li>
                                    <li><a asp-controller="Home" asp-action="Checkout">Оформление заказа</a></li>
                                    <li><a asp-controller="Cart" asp-action="Details">Корзина</a></li>
                                    <li><a asp-controller="Account" asp-action="Login">Вход</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a asp-controller="Home" asp-action="Blog">Список блогов</a></li>
                                    <li><a asp-controller="Home" asp-action="BlogSingle">Блог</a></li>
                                </ul>
                            </li>
                            <li><a asp-controller="Home" asp-action="Error404">Ошибка 404</a></li>
                            <li><a asp-controller="Home" asp-action="ContactUs">Контакты</a></li>
                            <li><a asp-controller="Employes" asp-action="Index">Сотрудники</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Поиск" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
<div class="left-sidebar">

    @await Component.InvokeAsync("Sections")

    @await Component.InvokeAsync("Brands")


    <div class="price-range">
        <!--price-range-->
        <h2>Диапазон цен</h2>
        <div class="well text-center">
            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2">
            <br/>
            <b class="pull-left">@(0.ToString("C0"))</b> 
            <b class="pull-right">@(600.ToString("C0"))</b>
        </div>
    </div><!--/price-range-->

    <div class="shipping text-center">
        <!--shipping-->
        <img src="images/home/shipping.jpg" alt=""/>
    </div><!--/shipping-->

</div>